port: 7890
allow-lan: true
mode: rule
log-level: info
unified-delay: true
global-client-fingerprint: chrome
dns:
  enable: true
  listen: :53
  ipv6: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  default-nameserver:
  - 223.5.5.5
  - 223.6.6.6
  nameserver:
  - https://dns.alidns.com/dns-query
  - https://doh.pub/dns-query
  fallback:
  - https://1.0.0.1/dns-query
  - tls://dns.google
  fallback-filter:
    geoip: true
    geoip-code: CN
    ipcidr:
    - 240.0.0.0/4
external-controller: 127.0.0.1:60000
proxy-groups:
  - name: ✈️ 节点选择
    type: select
    proxies:
      - ♻️ 自动选择
      -    DIRECT
      - ⚠️ 故障转移
      - ⚖️ 负载均衡
    use:
      - onlyno999-0001
  - name: ♻️ 自动选择
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 300
    tolerance: 100
    proxies:
    use:
      - onlyno999-0001
  - name: ⚠️ 故障转移
    type: fallback
    interval: 180
    tolerance: 50
    proxies:
    use:
      - onlyno999-0001
  - name: ⚖️ 负载均衡
    type: load-balance
    proxies:
    use:
      - onlyno999-0001
    url: https://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50
    strategy: consistent-hashing
rules:
- DOMAIN,clash.razord.top,DIRECT
- DOMAIN,yacd.haishan.me,DIRECT
- GEOIP,LAN,DIRECT
- GEOIP,CN,DIRECT
- MATCH, ✈️ 节点选择
